const card1 = document.querySelector("#card1");
const ventana1 = document.querySelector("#window1");
ventana1.addEventListener('click',()=>{
    card1.classList.add('apagar');
    card2.classList.remove('apagar');
    card3.classList.remove('apagar');
    card4.classList.remove('apagar');
    card5.classList.remove('apagar');
    card6.classList.remove('apagar');
    card7.classList.remove('apagar');
    card8.classList.remove('apagar');
    card9.classList.remove('apagar');
    card10.classList.remove('apagar');
});
const card2 = document.querySelector("#card2");
const ventana2 = document.querySelector("#window2");
ventana2.addEventListener('click',()=>{
    card2.classList.add('apagar');
    card1.classList.remove('apagar');
    card3.classList.remove('apagar');
    card4.classList.remove('apagar');
    card5.classList.remove('apagar');
    card6.classList.remove('apagar');
    card7.classList.remove('apagar');
    card8.classList.remove('apagar');
    card9.classList.remove('apagar');
    card10.classList.remove('apagar');
});
const card3 = document.querySelector("#card3");
const ventana3 = document.querySelector("#window3");
ventana3.addEventListener('click',()=>{
    card3.classList.add('apagar');
    card2.classList.remove('apagar');
    card4.classList.remove('apagar');
    card1.classList.remove('apagar');
    card5.classList.remove('apagar');
    card6.classList.remove('apagar');
    card7.classList.remove('apagar');
    card8.classList.remove('apagar');
    card9.classList.remove('apagar');
    card10.classList.remove('apagar');
});
const card4 = document.querySelector("#card4");
const ventana4 = document.querySelector("#window4");
ventana4.addEventListener('click',()=>{
    card4.classList.add('apagar');
    card2.classList.remove('apagar');
    card3.classList.remove('apagar');
    card1.classList.remove('apagar');
    card5.classList.remove('apagar');
    card6.classList.remove('apagar');
    card7.classList.remove('apagar');
    card8.classList.remove('apagar');
    card9.classList.remove('apagar');
    card10.classList.remove('apagar');
});
const card5 = document.querySelector("#card5");
const ventana5 = document.querySelector("#window5");
ventana5.addEventListener('click',()=>{
    card5.classList.add('apagar');
    card2.classList.remove('apagar');
    card3.classList.remove('apagar');
    card4.classList.remove('apagar');
    card1.classList.remove('apagar');
    card6.classList.remove('apagar');
    card7.classList.remove('apagar');
    card8.classList.remove('apagar');
    card9.classList.remove('apagar');
    card10.classList.remove('apagar');
});
const card6 = document.querySelector("#card6");
const ventana6 = document.querySelector("#window6");
ventana6.addEventListener('click',()=>{
    card6.classList.add('apagar');
    card2.classList.remove('apagar');
    card3.classList.remove('apagar');
    card4.classList.remove('apagar');
    card5.classList.remove('apagar');
    card1.classList.remove('apagar');
    card7.classList.remove('apagar');
    card8.classList.remove('apagar');
    card9.classList.remove('apagar');
    card10.classList.remove('apagar');
    
});
const card7 = document.querySelector("#card7");
const ventana7 = document.querySelector("#window7");

ventana7.addEventListener('click',()=>{
    card7.classList.add('apagar');
    card2.classList.remove('apagar');
    card3.classList.remove('apagar');
    card4.classList.remove('apagar');
    card5.classList.remove('apagar');
    card6.classList.remove('apagar');
    card1.classList.remove('apagar');
    card8.classList.remove('apagar');
    card9.classList.remove('apagar');
    card10.classList.remove('apagar');
});
const card8 = document.querySelector("#card8");
const ventana8 = document.querySelector("#window8");
ventana8.addEventListener('click',()=>{
    card8.classList.add('apagar');
    card2.classList.remove('apagar');
    card3.classList.remove('apagar');
    card4.classList.remove('apagar');
    card5.classList.remove('apagar');
    card6.classList.remove('apagar');
    card7.classList.remove('apagar');
    card1.classList.remove('apagar');
    card9.classList.remove('apagar');
    card10.classList.remove('apagar');
});
const card9 = document.querySelector("#card9");
const ventana9 = document.querySelector("#window9");
ventana9.addEventListener('click',()=>{
    card9.classList.add('apagar');
    card2.classList.remove('apagar');
    card3.classList.remove('apagar');
    card4.classList.remove('apagar');
    card5.classList.remove('apagar');
    card6.classList.remove('apagar');
    card7.classList.remove('apagar');
    card8.classList.remove('apagar');
    card1.classList.remove('apagar');
    card10.classList.remove('apagar');
});
const card10 = document.querySelector("#card10");
const ventana10 = document.querySelector("#window10");
ventana10.addEventListener('click',()=>{
    card10.classList.add('apagar');
    card2.classList.remove('apagar');
    card3.classList.remove('apagar');
    card4.classList.remove('apagar');
    card5.classList.remove('apagar');
    card6.classList.remove('apagar');
    card7.classList.remove('apagar');
    card8.classList.remove('apagar');
    card9.classList.remove('apagar');
    card1.classList.remove('apagar');
});